#!ruby

require "pathname"

$LOAD_PATH.unshift Pathname.new("#{File.dirname(__FILE__)}/../lib").cleanpath.to_s
puts Pathname.new("#{File.dirname(__FILE__)}/../lib").cleanpath.to_s
require "ht_sip_validator"

HathiTrust::ValidateSIPCommand.new(ARGV).exec
