---
package_checks:
 - Package::FileTypes: []
 - Package::MarcXML: []
 - Package::PDFCount: []
 - Package::ExtraFiles: []
 - Package::DuplicateFilenames: []
 - Package::FileBasenames: []
 - MetaYml::Exists: []
 - MetaYml::WellFormed: ['MetaYml::Exists']
 - MetaYml::PageOrder: ['MetaYml::WellFormed']
 - MetaYml::PageData::Presence: ['MetaYml::WellFormed']
 - MetaYml::PageData::PageTags: ['MetaYml::WellFormed']
 - MetaYml::PageData::Values: ['MetaYml::WellFormed']
 - MetaYml::PageData::Keys: ['MetaYml::WellFormed']
 - MetaYml::PageData::Files: ['MetaYml::WellFormed']
 - MetaYml::UnknownKeys: ['MetaYml::WellFormed']
 - MetaYml::RequiredKeys: ['MetaYml::WellFormed']
 - Checksums::Exists: []
 - Checksums::WellFormed: ['Checksums::Exists']
 - Checksums::FileListComplete: ['Checksums::WellFormed']
 - OCR::CoordinateFormat: []
 - Image::Count: []
 - Image::Sequence: []
